apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproapp
  labels:
    app: vproapp
spec:
  selector:
    matchLabels:
      app: vproapp
  replicas: 1      
  template:
    metadata:
      labels:
        app: vproapp
    spec:
      containers:
        - name: vproapp
#          image: vprofile/vprofileapp:V1
          image: {{ .Values.appimage }}
          # resources:
          #   limits:
          #     memory: "512Mi"
          #     cpu: "2000m"
          #   requests:
          #     memory: "256Mi"            
          #     cpu: "1000m"
          ports:
            - name: vproapp-port
              containerPort: 8080
      initContainers:
        - name: init-mydb
          image: alpine:latest
         # command: ['sh', '-c', 'until nslookup vprodb; do echo waiting for mydb; sleep 10; done;']
          command: ['sh', '-c', 'apk add --no-cache bind-tools && until nslookup vprodb; do echo waiting for mydb; sleep 10; done;']
          # command: ['sh', '-c', 'echo "Initiating mydb setup"; sleep 60']
        - name: init-memcache
          image: alpine:latest
          command: ['sh', '-c', 'apk add --no-cache bind-tools && until nslookup vprocache01; do echo waiting for memcache; sleep 2; done;']

          


