# apiVersion: v1
# kind: Service
# metadata:
#   name: vproapp-service
# spec:
#   selector:
#     app: vproapp
#   ports:
#     - port: 80
#       targetPort: vproapp-port
#       protocol: TCP
#   type: NodePort

 
apiVersion: v1
kind: Service
metadata:
  name: result
spec:
  selector:
      app: result
  ports:
    - port: 5001
      targetPort: result-app-port
      protocol: TCP
  type: LoadBalancer

